package com.my.route.model;

import java.util.Date;

public class Accounts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.account_name
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.account_type
     *
     * @mbggenerated
     */
    private Integer accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.appsecert
     *
     * @mbggenerated
     */
    private String appsecert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.source_id
     *
     * @mbggenerated
     */
    private String sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.isvoid
     *
     * @mbggenerated
     */
    private Integer isvoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.id
     *
     * @return the value of accounts.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.id
     *
     * @param id the value for accounts.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.account_name
     *
     * @return the value of accounts.account_name
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.account_name
     *
     * @param accountName the value for accounts.account_name
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.account_type
     *
     * @return the value of accounts.account_type
     *
     * @mbggenerated
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.account_type
     *
     * @param accountType the value for accounts.account_type
     *
     * @mbggenerated
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.appid
     *
     * @return the value of accounts.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.appid
     *
     * @param appid the value for accounts.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.appsecert
     *
     * @return the value of accounts.appsecert
     *
     * @mbggenerated
     */
    public String getAppsecert() {
        return appsecert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.appsecert
     *
     * @param appsecert the value for accounts.appsecert
     *
     * @mbggenerated
     */
    public void setAppsecert(String appsecert) {
        this.appsecert = appsecert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.source_id
     *
     * @return the value of accounts.source_id
     *
     * @mbggenerated
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.source_id
     *
     * @param sourceId the value for accounts.source_id
     *
     * @mbggenerated
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.created_at
     *
     * @return the value of accounts.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.created_at
     *
     * @param createdAt the value for accounts.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.isvoid
     *
     * @return the value of accounts.isvoid
     *
     * @mbggenerated
     */
    public Integer getIsvoid() {
        return isvoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.isvoid
     *
     * @param isvoid the value for accounts.isvoid
     *
     * @mbggenerated
     */
    public void setIsvoid(Integer isvoid) {
        this.isvoid = isvoid;
    }
}