package com.my.route.model;

import java.util.Date;

public class ClickBind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click_bind.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click_bind.click_event_id
     *
     * @mbggenerated
     */
    private Integer xmClickEventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click_bind.unbind_template_id
     *
     * @mbggenerated
     */
    private Integer unbindTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click_bind.bind_template_id
     *
     * @mbggenerated
     */
    private Integer bindTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click_bind.reset_bind_template_id
     *
     * @mbggenerated
     */
    private Integer resetBindTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click_bind.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column click_bind.isvoid
     *
     * @mbggenerated
     */
    private Integer isvoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click_bind.id
     *
     * @return the value of click_bind.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click_bind.id
     *
     * @param id the value for click_bind.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click_bind.click_event_id
     *
     * @return the value of click_bind.click_event_id
     *
     * @mbggenerated
     */
    public Integer getXmClickEventId() {
        return xmClickEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click_bind.click_event_id
     *
     * @param xmClickEventId the value for click_bind.click_event_id
     *
     * @mbggenerated
     */
    public void setXmClickEventId(Integer xmClickEventId) {
        this.xmClickEventId = xmClickEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click_bind.unbind_template_id
     *
     * @return the value of click_bind.unbind_template_id
     *
     * @mbggenerated
     */
    public Integer getUnbindTemplateId() {
        return unbindTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click_bind.unbind_template_id
     *
     * @param unbindTemplateId the value for click_bind.unbind_template_id
     *
     * @mbggenerated
     */
    public void setUnbindTemplateId(Integer unbindTemplateId) {
        this.unbindTemplateId = unbindTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click_bind.bind_template_id
     *
     * @return the value of click_bind.bind_template_id
     *
     * @mbggenerated
     */
    public Integer getBindTemplateId() {
        return bindTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click_bind.bind_template_id
     *
     * @param bindTemplateId the value for click_bind.bind_template_id
     *
     * @mbggenerated
     */
    public void setBindTemplateId(Integer bindTemplateId) {
        this.bindTemplateId = bindTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click_bind.reset_bind_template_id
     *
     * @return the value of click_bind.reset_bind_template_id
     *
     * @mbggenerated
     */
    public Integer getResetBindTemplateId() {
        return resetBindTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click_bind.reset_bind_template_id
     *
     * @param resetBindTemplateId the value for click_bind.reset_bind_template_id
     *
     * @mbggenerated
     */
    public void setResetBindTemplateId(Integer resetBindTemplateId) {
        this.resetBindTemplateId = resetBindTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click_bind.created_at
     *
     * @return the value of click_bind.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click_bind.created_at
     *
     * @param createdAt the value for click_bind.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column click_bind.isvoid
     *
     * @return the value of click_bind.isvoid
     *
     * @mbggenerated
     */
    public Integer getIsvoid() {
        return isvoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column click_bind.isvoid
     *
     * @param isvoid the value for click_bind.isvoid
     *
     * @mbggenerated
     */
    public void setIsvoid(Integer isvoid) {
        this.isvoid = isvoid;
    }
}