package com.my.route.mapper;

import com.my.route.model.Accounts;

import java.util.HashMap;
import java.util.List;

public interface AccountsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated
     */
    int insert(Accounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated
     */
    int insertSelective(Accounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated
     */
    Accounts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Accounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Accounts record);

    List<Accounts> selectList();

    List<Integer> selectIds();

    List<Accounts> selectListByPage(HashMap<String, Integer> offsetLimit);

    int getCount();

    List<Accounts> query(HashMap<String, Object> queryMap);

    int queryCount(HashMap<String, Object> queryMap);

    Accounts selectByAppid(String appid);

    Accounts selectBySourceId(String gh_id);
}